'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import {
  Alert,
  Badge,
  Button,
  Field,
  PageHeader,
  SectionCard,
  Skeleton,
  StatusBadge,
  Textarea,
} from '@namo/ui';
import { api } from '@/lib/api';
import { formatDate } from '@/lib/format';

interface Extracted {
  title?: string;
  description?: string;
  ageMinMonths?: number;
  ageMaxMonths?: number;
  domains?: { name: string; code: string; questions: number }[];
}

interface Warning {
  field: string;
  message: string;
}

export default function UploadReviewPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const queryClient = useQueryClient();
  const uploadQuery = useQuery({
    queryKey: ['admin-upload', id],
    queryFn: () => api().adminGetUpload(id),
  });

  const [notes, setNotes] = useState('');
  const reviewMutation = useMutation({
    mutationFn: (payload: { status: 'APPROVED' | 'REJECTED' | 'NEEDS_REVIEW' }) =>
      api().adminReviewUpload(id, { status: payload.status, reviewNotes: notes || undefined }),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['admin-upload', id] });
      await queryClient.invalidateQueries({ queryKey: ['admin-uploads'] });
    },
  });

  const extractMutation = useMutation({
    mutationFn: () => api().adminRunExtraction(id),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['admin-upload', id] });
    },
  });

  if (uploadQuery.isLoading) {
    return (
      <div className="space-y-4">
        <PageHeader title="Loading upload…" />
        <Skeleton className="h-96" />
      </div>
    );
  }
  if (uploadQuery.isError || !uploadQuery.data) {
    return (
      <div className="space-y-4">
        <PageHeader title="Upload not found" />
        <Alert variant="error">We couldn&apos;t load this upload.</Alert>
      </div>
    );
  }

  const upload = uploadQuery.data;
  const extracted = (upload.extracted ?? {}) as Extracted;
  const warnings: Warning[] = Array.isArray(upload.warnings) ? (upload.warnings as Warning[]) : [];

  return (
    <div className="space-y-5">
      <PageHeader
        title={upload.fileName}
        description={`${(upload.sizeBytes / 1024).toFixed(0)} KB · ${upload.mimeType}`}
        actions={
          <Link href="/uploads" className="text-sm font-medium text-ink-muted hover:text-ink">
            ← All uploads
          </Link>
        }
      />

      <div className="flex flex-wrap items-center gap-2">
        <StatusBadge value={upload.status} />
        {upload.confidence != null && (
          <Badge tone={upload.confidence > 0.85 ? 'teal' : 'gold'}>
            {(upload.confidence * 100).toFixed(0)}% confidence
          </Badge>
        )}
        {warnings.length > 0 && <Badge tone="gold">{warnings.length} warning{warnings.length === 1 ? '' : 's'}</Badge>}
        <span className="text-xs text-ink-soft">
          Uploaded {formatDate(upload.createdAt)} by {upload.createdBy.fullName}
        </span>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <SectionCard
          title="Source document"
          description="PDF preview is rendered in production. Placeholder here shows file metadata."
        >
          <div className="aspect-[3/4] rounded-2xl border border-dashed border-sand-300 bg-sand-100/40 p-6 text-center">
            <div className="flex h-full flex-col items-center justify-center gap-2 text-ink-soft">
              <span className="text-4xl">📄</span>
              <p className="text-sm font-medium text-ink">{upload.fileName}</p>
              <p className="text-xs">{upload.storageKey}</p>
            </div>
          </div>
        </SectionCard>

        <SectionCard
          title="Extracted structure"
          description="Generated by the AI extraction pipeline. Verify before publishing."
          actions={
            upload.status === 'UPLOADED' && (
              <Button
                size="sm"
                onClick={() => extractMutation.mutate()}
                loading={extractMutation.isPending}
              >
                Run AI extraction
              </Button>
            )
          }
        >
          {upload.status === 'UPLOADED' ? (
            <p className="text-sm text-ink-soft">
              No extraction has been run yet. Click <strong>Run AI extraction</strong> to generate a draft.
            </p>
          ) : Object.keys(extracted).length === 0 ? (
            <p className="text-sm text-ink-soft">No structured output available.</p>
          ) : (
            <div className="space-y-4">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">Title</p>
                <p className="text-sm text-ink">{extracted.title}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">Description</p>
                <p className="text-sm text-ink-muted">{extracted.description}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">Age band</p>
                <p className="text-sm text-ink">
                  {extracted.ageMinMonths}–{extracted.ageMaxMonths} months
                </p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-soft">Domains</p>
                <ul className="mt-1 space-y-1">
                  {extracted.domains?.map((domain) => (
                    <li
                      key={domain.code}
                      className="flex items-center justify-between rounded-xl bg-sand-100/60 px-3 py-1.5 text-sm"
                    >
                      <span className="text-ink">{domain.name}</span>
                      <span className="text-xs text-ink-soft">
                        {domain.code} · {domain.questions} questions
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </SectionCard>
      </div>

      {warnings.length > 0 && (
        <SectionCard title="Warnings" description="The extractor flagged the following items.">
          <ul className="space-y-2">
            {warnings.map((warning, index) => (
              <li
                key={index}
                className="flex items-start gap-3 rounded-xl bg-gold-400/8 px-3 py-2 text-sm"
              >
                <Badge tone="gold">{warning.field}</Badge>
                <span className="text-ink">{warning.message}</span>
              </li>
            ))}
          </ul>
        </SectionCard>
      )}

      {upload.status === 'NEEDS_REVIEW' && (
        <SectionCard
          title="Reviewer decision"
          description="AI extraction MUST NEVER auto-publish — a human must approve."
        >
          <div className="space-y-3">
            <Field label="Review notes">
              <Textarea
                rows={3}
                value={notes}
                onChange={(event) => setNotes(event.target.value)}
                placeholder="Explain any corrections, exclusions or follow-ups…"
              />
            </Field>
            <div className="flex flex-wrap gap-2">
              <Button
                onClick={() => reviewMutation.mutate({ status: 'APPROVED' })}
                loading={reviewMutation.isPending && reviewMutation.variables?.status === 'APPROVED'}
              >
                Approve
              </Button>
              <Button
                variant="ghost"
                onClick={() => reviewMutation.mutate({ status: 'NEEDS_REVIEW' })}
                loading={reviewMutation.isPending && reviewMutation.variables?.status === 'NEEDS_REVIEW'}
              >
                Save & keep reviewing
              </Button>
              <Button
                variant="danger"
                onClick={() => reviewMutation.mutate({ status: 'REJECTED' })}
                loading={reviewMutation.isPending && reviewMutation.variables?.status === 'REJECTED'}
              >
                Reject
              </Button>
            </div>
          </div>
        </SectionCard>
      )}

      {upload.reviewNotes && (
        <SectionCard title={`Reviewed by ${upload.reviewedBy?.fullName ?? 'Admin'}`}>
          <p className="text-sm text-ink-muted">{upload.reviewNotes}</p>
          {upload.reviewedAt && (
            <p className="mt-1 text-xs text-ink-soft">{formatDate(upload.reviewedAt)}</p>
          )}
        </SectionCard>
      )}
    </div>
  );
}
